SENTINEL_API_URL = "https://your-sentinel-api.azure.com/query"
SENTINEL_AUTH_TOKEN = "your_sentinel_auth_token"
PLAYBOOK_ACTIVATION_URL = "https://your-api.com/activate"
PLAYBOOK_ACTIVATION_AUTH_TOKEN = "your_playbook_auth_token"
